--- #YAML:1.0
name:                IO-File-MultiLines
version:             0.02
abstract:            ~
license:             ~
author:              
    - A. U. Thor <woosley@localdomain>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::File:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
